[package]
name = "j1r4"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
clearscreen = "4.0.2"
colored = "3.0.0"
ellipse = "0.2.0"
itertools = "0.14.0"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.142"

[dev-dependencies]
tempfile = "3.20.0"
